### PR TITLE
Setting up Travis-CI

### PR DESCRIPTION
**Pull request by juanshishido**
Basic files and structure. Will need to update as we move forward.

### CODE REVIEW

**Comment by juanshishido** [comment]
Need to fix the `.travis.yml` file.

**Comment by juanshishido** [comment]
Need to figure this out tonight. **Do not merge.**

**Comment by juanshishido** [comment]
Simplified `.travis.yml`&mdash;now passing.

**Comment by juanshishido** [comment]
Ready to be merged.

**Comment by juanshishido** [comment]
FYI, `rebase`d to keep commit history clean. Thanks for the suggestion, @robinkalia!

**Comment by robinkalia** [comment]
LGTM

**Pull request merged**
